=== Pixoll/PoCoPI/config/config.xsd
<?xml version="1.0" encoding="utf-8"?>
<!-- Created with Liquid Technologies Online Tools 1.0 (https://www.liquid-technologies.com) -->
<xs:schema elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="Label">
    <xs:annotation>
      <xs:documentation>Label for which to identify the element</xs:documentation>
    </xs:annotation>

    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="Img">
    <xs:annotation>
      <xs:documentation>
        HTML &lt;img&gt; tag. See https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img
      </xs:documentation>
    </xs:annotation>

    <xs:attribute name="src" type="xs:anyURI" use="required">
      <xs:annotation>
        <xs:documentation>
          Where the image is located. See https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img#src
        </xs:documentation>
      </xs:annotation>

      <xs:simpleType>
        <xs:restriction base="xs:anyURI">
          <xs:minLength value="1"/>
        </xs:restriction>
      </xs:simpleType>
    </xs:attribute>

    <xs:attribute name="alt" type="xs:string" use="required">
      <xs:annotation>
        <xs:documentation>
          Needed for accessibility reasons (screen readers, image loading failure, etc.).
          See https://developer.mozilla.org/en-US/docs/Web/HTML/Reference/Elements/img#alt
        </xs:documentation>
      </xs:annotation>
    </xs:attribute>
  </xs:complexType>

  <xs:element name="config">
    <xs:complexType>
      <xs:all>
        <xs:element name="groups">
          <xs:annotation>
            <xs:documentation>List of test groups</xs:documentation>
          </xs:annotation>

          <xs:complexType>
            <xs:sequence>
              <xs:element name="group" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>A test group</xs:documentation>
                </xs:annotation>

                <xs:complexType>
                  <xs:all>
                    <xs:element name="probability" type="xs:decimal">
                      <xs:annotation>
                        <xs:documentation>
                          The chance of this group to be selected.
                          The sum of all the probabilities of all the groups should be 1.
                        </xs:documentation>
                      </xs:annotation>

                      <xs:simpleType>
                        <xs:restriction base="xs:decimal">
                          <xs:minExclusive value="0"/>
                          <xs:maxInclusive value="1"/>
                        </xs:restriction>
                      </xs:simpleType>
                    </xs:element>

                    <xs:element name="protocol" type="xs:string">
                      <xs:annotation>
                        <xs:documentation>Name of the protocol to use</xs:documentation>
                      </xs:annotation>
                    </xs:element>
                  </xs:all>

                  <xs:attribute name="label" type="Label" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>

        <xs:element name="protocols">
          <xs:annotation>
            <xs:documentation>List of protocols the test groups will use</xs:documentation>
          </xs:annotation>

          <xs:complexType>
            <xs:sequence>
              <xs:element name="protocol" maxOccurs="unbounded">
                <xs:annotation>
                  <xs:documentation>A testing protocol</xs:documentation>
                </xs:annotation>

                <xs:complexType>
                  <xs:sequence>
                    <xs:element name="phases">
                      <xs:annotation>
                        <xs:documentation>Phases of the testing protocol</xs:documentation>
                      </xs:annotation>

                      <xs:complexType>
                        <xs:sequence>
                          <xs:element name="phase">
                            <xs:annotation>
                              <xs:documentation>Phase of a testing protocol</xs:documentation>
                            </xs:annotation>

                            <xs:complexType>
                              <xs:all>
                                <xs:element name="img" type="Img"/>

                                <xs:element name="options">
                                  <xs:annotation>
                                    <xs:documentation>List of options</xs:documentation>
                                  </xs:annotation>

                                  <xs:complexType>
                                    <xs:sequence>
                                      <xs:element name="img" type="Img" minOccurs="8" maxOccurs="8"/>
                                    </xs:sequence>
                                  </xs:complexType>
                                </xs:element>

                                <xs:element name="correct" type="xs:integer">
                                  <xs:annotation>
                                    <xs:documentation>The correct option</xs:documentation>
                                  </xs:annotation>

                                  <xs:simpleType>
                                    <xs:restriction base="xs:integer">
                                      <xs:minInclusive value="1"/>
                                      <xs:maxInclusive value="8"/>
                                    </xs:restriction>
                                  </xs:simpleType>
                                </xs:element>
                              </xs:all>
                            </xs:complexType>
                          </xs:element>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                  </xs:sequence>

                  <xs:attribute name="label" type="Label" use="required"/>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:all>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Pixoll/PoCoPI/apps/backend/config/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="config.xsd">
  <groups>
    <group label="control">
      <probability>0.8</probability>
      <protocol>control</protocol>
    </group>
  </groups>

  <protocols>
    <protocol label="control">
      <phases>
        <phase>
          <img src="control1.png" alt="question image"/>
          <correct>1</correct>
          <options>
            <img src="control1_option1.png" alt="option 1"/>
            <img src="control1_option2.png" alt="option 2"/>
            <img src="control1_option3.png" alt="option 3"/>
            <img src="control1_option4.png" alt="option 4"/>
            <img src="control1_option5.png" alt="option 5"/>
            <img src="control1_option6.png" alt="option 6"/>
            <img src="control1_option7.png" alt="option 7"/>
            <img src="control1_option8.png" alt="option 8"/>
          </options>
        </phase>
      </phases>
    </protocol>
  </protocols>
</config>
